version: "3.1"

services:
  db:
    image: postgres
    container_name: techforge_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
